export const DELETE_USER: "DELETE_USER" = "DELETE_USER";

export const GET_USER_REQUEST: "GET_USER_REQUEST" = "GET_USER_REQUEST";
export const GET_USER_SUCCESS: "GET_USER_SUCCESS" = "GET_USER_SUCCESS";
export const GET_USER_FAILED: "GET_USER_FAILED" = "GET_USER_FAILED";

export const SET_AUTH_CHECKED: "SET_AUTH_CHECKED" = "SET_AUTH_CHECKED";

export const EDIT_PROFILE_SUCCESS: "EDIT_PROFILE_SUCCESS" =
  "EDIT_PROFILE_SUCCESS";
export const EDIT_PROFILE_FAILED: "EDIT_PROFILE_FAILED" = "EDIT_PROFILE_FAILED";
export const EDIT_PROFILE_REQUEST: "EDIT_PROFILE_REQUEST" =
  "EDIT_PROFILE_REQUEST";

export const UPDATE_USER_DATA: "UPDATE_USER_DATA" = "UPDATE_USER_DATA";